<?php
declare(strict_types=1);
require dirname(__DIR__).'/src/bootstrap.php';
use FudgeDonuts\{AnalyticsService,CostAccountingService,Database,DisputeService,ReportingService};
require_admin_roles(['super_admin','admin']);
$db=Database::connection();$r=new ReportingService($db);
$overview=$r->overview($_GET['start']??null,$_GET['end']??null);$statuses=$r->byStatus();$packs=$r->packPerformance();$flavors=$r->flavorPerformance();$daily=$r->dailySales(30);
$analyticsEnabled=(env('ANALYTICS_ENABLED','0')??'0')==='1';$analytics=new AnalyticsService($db);$funnel=$analytics->funnel(30);$sources=$analytics->sources(30);
$margin=(new CostAccountingService($db))->summary($_GET['start']??null,$_GET['end']??null);$disputes=(new DisputeService($db))->stats();
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="<?=htmlspecialchars(asset_url('/assets/app.css'))?>"><title>Reports · Admin</title></head><body class="admin-body">
<header class="admin-topbar"><a class="admin-brand" href="/admin.php">Fudge Donuts <span>Admin</span></a><nav><a href="/admin.php">Dashboard</a><a href="/admin-flavors.php">Flavors</a><a href="/admin-packs.php">Packs</a><a href="/admin-orders.php">Orders</a><a href="/admin-customers.php">Customers</a><a href="/admin-gift-cards.php">Gift Cards</a><a href="/admin-inventory.php">Inventory</a><a href="/admin-shipping.php">Shipping</a><a href="/admin-tax.php">Tax</a><a href="/admin-promotions.php">Promotions</a><a href="/admin-content.php">Content</a><a class="active" href="/admin-reports.php">Reports</a></nav></header>
<main class="admin-shell"><p class="eyebrow">Performance</p><h1>Store reports</h1>
<form method="get" class="inline-admin"><input type="date" name="start" value="<?=htmlspecialchars((string)($_GET['start']??''))?>"><input type="date" name="end" value="<?=htmlspecialchars((string)($_GET['end']??''))?>"><button class="button secondary">Filter</button><a class="button" href="/admin-report.csv.php">Export CSV</a></form>
<div class="metric-grid"><article><span>Orders</span><strong><?=(int)$overview['orders']?></strong></article><article><span>Revenue</span><strong><?=money((int)$overview['revenue_cents'])?></strong></article><article><span>Average order</span><strong><?=money((int)$overview['aov_cents'])?></strong></article><article><span>Discounts</span><strong><?=money((int)$overview['discount_cents'])?></strong></article><article><span>Tax collected</span><strong><?=money((int)$overview['tax_cents'])?></strong></article></div>
<section><div class="panel-head"><div><p class="eyebrow">Payment risk</p><h2>Chargeback exposure</h2></div><a href="/admin-disputes.php">Review disputes →</a></div><div class="metric-grid"><article><span>Open disputes</span><strong><?=(int)$disputes['open']?></strong></article><article><span>Open amount</span><strong><?=money((int)$disputes['open_amount_cents'])?></strong></article><article><span>Lost</span><strong><?=(int)$disputes['lost']?></strong></article><article><span>Won</span><strong><?=(int)$disputes['won']?></strong></article></div></section>
<section><div class="panel-head"><div><p class="eyebrow">Profitability</p><h2>Gross margin</h2></div><a href="/admin-costs.php">Manage costs →</a></div><div class="metric-grid"><article><span>Costed orders</span><strong><?=(int)$margin['orders']?></strong></article><article><span>Merchandise revenue</span><strong><?=money((int)$margin['revenue_basis_cents'])?></strong></article><article><span>Estimated COGS</span><strong><?=money((int)$margin['cost_cents'])?></strong></article><article><span>Gross margin</span><strong><?=money((int)$margin['margin_cents'])?></strong></article><article><span>Margin %</span><strong><?=htmlspecialchars(number_format((float)$margin['margin_percent'],2))?>%</strong></article></div></section>
<?php if($analyticsEnabled):?><section><h2>30-day conversion funnel</h2><div class="metric-grid"><article><span>Visitors</span><strong><?=(int)$funnel['visitors']?></strong></article><article><span>Builder</span><strong><?=(int)$funnel['builder_visitors']?></strong></article><article><span>Cart</span><strong><?=(int)$funnel['cart_visitors']?></strong></article><article><span>Checkout</span><strong><?=(int)$funnel['checkout_visitors']?></strong></article><article><span>Purchases</span><strong><?=(int)$funnel['purchases']?></strong></article><article><span>Conversion</span><strong><?=htmlspecialchars(number_format((float)$funnel['conversion_rate'],2))?>%</strong></article><article><span>Attributed revenue</span><strong><?=money((int)$funnel['revenue_cents'])?></strong></article></div></section><section><h2>Acquisition sources · 30 days</h2><table><thead><tr><th>Source</th><th>Medium</th><th>Campaign</th><th>Orders</th><th>Revenue</th></tr></thead><tbody><?php if(!$sources):?><tr><td colspan="5">No attributed orders yet.</td></tr><?php endif;?><?php foreach($sources as $s):?><tr><td><?=htmlspecialchars($s['source'])?></td><td><?=htmlspecialchars($s['medium']?:'—')?></td><td><?=htmlspecialchars($s['campaign']?:'—')?></td><td><?=(int)$s['orders']?></td><td><?=money((int)$s['revenue_cents'])?></td></tr><?php endforeach;?></tbody></table></section><?php endif;?>
<div class="report-grid"><section><h2>Pack performance</h2><table><thead><tr><th>Pack</th><th>Boxes</th><th>Revenue</th></tr></thead><tbody><?php foreach($packs as $p):?><tr><td><?=(int)$p['pack_size']?> pack</td><td><?=(int)$p['boxes']?></td><td><?=money((int)$p['revenue_cents'])?></td></tr><?php endforeach;?></tbody></table></section>
<section><h2>Flavor popularity</h2><table><thead><tr><th>Flavor</th><th>Donuts</th></tr></thead><tbody><?php foreach($flavors as $f):?><tr><td><?=htmlspecialchars($f['name'])?></td><td><?=(int)$f['units']?></td></tr><?php endforeach;?></tbody></table></section></div>
<section><h2>Order status</h2><table><thead><tr><th>Status</th><th>Orders</th><th>Revenue</th></tr></thead><tbody><?php foreach($statuses as $s):?><tr><td><?=htmlspecialchars($s['status'])?></td><td><?=(int)$s['orders']?></td><td><?=money((int)$s['revenue_cents'])?></td></tr><?php endforeach;?></tbody></table></section>
</main></body></html>
