<?php
declare(strict_types=1);
require dirname(__DIR__).'/src/bootstrap.php';
use FudgeDonuts\{AdminAuditService,Database,SupplierPurchasingService};
require_admin_roles(['super_admin','admin','fulfillment']);

$db=Database::connection();$svc=new SupplierPurchasingService($db);$audit=new AdminAuditService($db);$error='';$notice='';
$id=(int)($_GET['id']??$_POST['po_id']??0);
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf($_POST['_csrf']??null);
 try{
  $action=(string)($_POST['action']??'');
  if($action==='create'){
    $supplierId=(int)($_POST['supplier_id']??0);$itemIds=(array)($_POST['supplier_item_id']??[]);$qtys=(array)($_POST['quantity_ordered']??[]);$lines=[];
    $count=max(count($itemIds),count($qtys));for($i=0;$i<$count;$i++)$lines[]=['supplier_item_id'=>(int)($itemIds[$i]??0),'quantity_ordered'=>(float)($qtys[$i]??0)];
    $id=$svc->createPurchaseOrder($supplierId,$lines,(string)($_POST['expected_at']??''),(string)($_POST['notes']??''),(int)$_SESSION['admin_id']);
    $audit->record((int)$_SESSION['admin_id'],'purchase_order_created','purchase_order',$id,'Purchase order created.',[],['supplier_id'=>$supplierId]);
    $notice='Purchase order created.';
  }elseif($action==='order'){
    $svc->markOrdered($id);$audit->record((int)$_SESSION['admin_id'],'purchase_order_ordered','purchase_order',$id,'Purchase order marked ordered.');$notice='Purchase order marked ordered.';
  }elseif($action==='cancel'){
    require_admin_roles(['super_admin','admin']);$svc->cancel($id);$audit->record((int)$_SESSION['admin_id'],'purchase_order_cancelled','purchase_order',$id,'Purchase order cancelled.');$notice='Purchase order cancelled.';
  }elseif($action==='receive'){
    $itemId=(int)($_POST['po_item_id']??0);$lotId=$svc->receive($itemId,$_POST,(int)$_SESSION['admin_id']);
    $audit->record((int)$_SESSION['admin_id'],'purchase_order_received','ingredient_lot',$lotId,'Purchase-order receipt created traceable ingredient lot.',[],['purchase_order_id'=>$id,'purchase_order_item_id'=>$itemId]);
    $notice='Receipt posted and ingredient lot created.';
  }else throw new InvalidArgumentException('Unsupported purchase-order action.');
 }catch(Throwable $e){$error=$e->getMessage();}
}
$status=trim((string)($_GET['status']??''));try{$orders=$svc->purchaseOrders($status?:null);}catch(Throwable $e){$error=$e->getMessage();$status='';$orders=$svc->purchaseOrders();}
$suppliers=$svc->suppliers(true);$allItems=$svc->items(null,true);$current=$id?$svc->purchaseOrder($id):null;$summary=$svc->summary();
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Purchase Orders · Fudge Donuts Admin</title><link rel="stylesheet" href="<?=htmlspecialchars(asset_url('/assets/app.css'))?>"></head><body class="admin-body">
<a class="skip-link" href="#admin-main">Skip to admin content</a>
<header class="admin-topbar"><a class="admin-brand" href="/admin.php">Fudge Donuts <span>Admin</span></a><nav><a href="/admin.php">Dashboard</a><a href="/admin-suppliers.php">Suppliers</a><a class="active" href="/admin-purchase-orders.php">Purchase Orders</a><a href="/admin-procurement-plan.php">Procurement Plan</a><a href="/admin-ingredient-lots.php">Ingredients</a><a href="/admin-recipes.php">Recipes</a><a href="/admin-batches.php">Batches</a></nav></header>
<main id="admin-main" tabindex="-1" class="admin-shell">
<div class="admin-page-head"><div><p class="eyebrow">Procurement</p><h1>Purchase Orders</h1><p class="admin-welcome">Order ingredients, receive supplier lots, and preserve quantity and cost traceability.</p></div></div>
<?php if($error):?><div class="notice error" role="alert"><?=htmlspecialchars($error)?></div><?php endif;?><?php if($notice):?><div class="notice" role="status"><?=htmlspecialchars($notice)?></div><?php endif;?>
<section class="dashboard-kpis"><article class="kpi-card"><span>Open POs</span><strong><?=$summary['open_po']?></strong></article><article class="kpi-card <?=$summary['overdue_po']?'kpi-alert':''?>"><span>Overdue</span><strong><?=$summary['overdue_po']?></strong></article><article class="kpi-card"><span>Open value</span><strong><?=money((int)$summary['open_value_cents'])?></strong></article><article class="kpi-card"><span>Active suppliers</span><strong><?=$summary['active_suppliers']?></strong></article></section>

<div class="order-filters"><a class="<?=!$status?'active':''?>" href="/admin-purchase-orders.php">All</a><?php foreach(['draft','ordered','partially_received','received','cancelled'] as $s):?><a class="<?=$status===$s?'active':''?>" href="/admin-purchase-orders.php?status=<?=$s?>"><?=htmlspecialchars(ucwords(str_replace('_',' ',$s)))?></a><?php endforeach;?></div>

<section class="dashboard-grid dashboard-secondary"><div class="dashboard-panel"><h2>Purchase order ledger</h2><div class="dashboard-table-wrap"><table class="dashboard-table"><thead><tr><th>PO</th><th>Supplier</th><th>Status</th><th>Expected</th><th>Value</th></tr></thead><tbody><?php if(!$orders):?><tr><td colspan="5" class="empty-cell">No purchase orders.</td></tr><?php endif;?><?php foreach($orders as $po):?><tr><td><a href="/admin-purchase-orders.php?id=<?=(int)$po['id']?>"><strong><?=htmlspecialchars($po['po_number'])?></strong></a><small><?=htmlspecialchars($po['created_at'])?></small></td><td><?=htmlspecialchars($po['supplier_name'])?></td><td><?=htmlspecialchars(ucwords(str_replace('_',' ',$po['status'])))?></td><td><?=htmlspecialchars((string)$po['expected_at'])?></td><td><?=money((int)round((float)$po['total_cents']))?></td></tr><?php endforeach;?></tbody></table></div></div>

<div class="dashboard-panel"><h2>Create purchase order</h2><form method="post" class="admin-form"><input type="hidden" name="_csrf" value="<?=htmlspecialchars(csrf_token())?>"><input type="hidden" name="action" value="create"><label>Supplier<select name="supplier_id" required><option value="">Choose supplier</option><?php foreach($suppliers as $s):?><option value="<?=(int)$s['id']?>"><?=htmlspecialchars($s['name'])?></option><?php endforeach;?></select></label><label>Expected date<input type="date" name="expected_at"></label><label>Notes<textarea name="notes"></textarea></label><div class="po-line-editor"><?php for($i=0;$i<8;$i++):?><div class="po-line-row"><label>Item<select name="supplier_item_id[]"><option value="">—</option><?php foreach($allItems as $it):?><option value="<?=(int)$it['id']?>"><?=htmlspecialchars($it['supplier_name'].' · '.$it['ingredient_name'].' · '.$it['quantity_unit'])?></option><?php endforeach;?></select></label><label>Quantity<input type="number" name="quantity_ordered[]" step="0.001" min="0.001"></label></div><?php endfor;?></div><button class="button">Create draft PO</button></form></div></section>

<?php if($current):?><section class="dashboard-panel"><div class="panel-head"><div><p class="eyebrow"><?=htmlspecialchars($current['supplier_name'])?></p><h2><?=htmlspecialchars($current['po_number'])?></h2><p><?=htmlspecialchars(ucwords(str_replace('_',' ',$current['status'])))?><?php if($current['expected_at']):?> · Expected <?=htmlspecialchars($current['expected_at'])?><?php endif;?></p></div><div class="actions"><?php if($current['status']==='draft'):?><form method="post"><input type="hidden" name="_csrf" value="<?=htmlspecialchars(csrf_token())?>"><input type="hidden" name="action" value="order"><input type="hidden" name="po_id" value="<?=$id?>"><button class="button">Mark ordered</button></form><?php endif;?><?php if(in_array($current['status'],['draft','ordered'],true) && admin_has_role(['super_admin','admin'])):?><form method="post"><input type="hidden" name="_csrf" value="<?=htmlspecialchars(csrf_token())?>"><input type="hidden" name="action" value="cancel"><input type="hidden" name="po_id" value="<?=$id?>"><button class="button secondary">Cancel PO</button></form><?php endif;?></div></div>
<div class="dashboard-table-wrap"><table class="dashboard-table"><thead><tr><th>Ingredient</th><th>Ordered</th><th>Received</th><th>Remaining</th><th>Unit cost</th></tr></thead><tbody><?php foreach($current['items'] as $item):?><tr><td><strong><?=htmlspecialchars($item['ingredient_name'])?></strong></td><td><?=htmlspecialchars((string)$item['quantity_ordered'].' '.$item['quantity_unit'])?></td><td><?=htmlspecialchars((string)$item['quantity_received'].' '.$item['quantity_unit'])?></td><td><?=htmlspecialchars((string)$item['remaining_quantity'].' '.$item['quantity_unit'])?></td><td><?=money((int)$item['unit_cost_cents'])?></td></tr><?php if(in_array($current['status'],['ordered','partially_received'],true) && (float)$item['remaining_quantity']>0):?><tr class="po-receive-row"><td colspan="5"><form method="post" class="inline-admin"><input type="hidden" name="_csrf" value="<?=htmlspecialchars(csrf_token())?>"><input type="hidden" name="action" value="receive"><input type="hidden" name="po_id" value="<?=$id?>"><input type="hidden" name="po_item_id" value="<?=(int)$item['id']?>"><label>Receive quantity<input type="number" name="quantity_received" step="0.001" min="0.001" max="<?=htmlspecialchars((string)$item['remaining_quantity'])?>" required></label><label>Supplier lot<input name="supplier_lot_code" required maxlength="120"></label><label>Received at<input type="datetime-local" name="received_at" required></label><label>Best by<input type="date" name="best_by_date"></label><label>Notes<input name="notes" maxlength="500"></label><button class="button secondary">Receive lot</button></form></td></tr><?php endif;?><?php endforeach;?></tbody></table></div>
<?php if($current['receipts']):?><h3>Receipt history</h3><div class="dashboard-table-wrap"><table class="dashboard-table"><thead><tr><th>Ingredient</th><th>Supplier lot</th><th>Quantity</th><th>Received</th></tr></thead><tbody><?php foreach($current['receipts'] as $r):?><tr><td><?=htmlspecialchars($r['ingredient_name'])?></td><td><a href="/admin-ingredient-lots.php?id=<?=(int)$r['ingredient_lot_id']?>"><?=htmlspecialchars($r['supplier_lot_code'])?></a></td><td><?=htmlspecialchars((string)$r['quantity_received'])?></td><td><?=htmlspecialchars($r['received_at'])?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?>
</section><?php endif;?>
</main></body></html>