<?php
declare(strict_types=1);
require dirname(__DIR__).'/src/bootstrap.php';
use FudgeDonuts\{AdminAuditService,Database,InventoryService};
require_admin_roles(['super_admin','admin','fulfillment']);
$db=Database::connection();$svc=new InventoryService($db);$audit=new AdminAuditService($db);$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf($_POST['_csrf']??null);
 try{$flavorId=(int)$_POST['flavor_id'];$before=[];foreach($svc->rows() as $row)if((int)$row['id']===$flavorId){$before=$row;break;}$svc->setInventory($flavorId,!empty($_POST['track_inventory']),(int)$_POST['stock_on_hand'],(int)$_POST['low_stock_threshold']);$after=[];foreach($svc->rows() as $row)if((int)$row['id']===$flavorId){$after=$row;break;}$audit->record((int)$_SESSION['admin_id'],'inventory_updated','flavor',$flavorId,'Flavor inventory updated.',$before,$after);header('Location: /admin-inventory.php');exit;}catch(Throwable $e){$error=$e->getMessage();}
}
$rows=$svc->rows();$reservationStats=$svc->reservationStats();
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/assets/app.css"><title>Inventory · Admin</title></head><body class="admin-body">
<header class="admin-topbar"><a class="admin-brand" href="/admin.php">Fudge Donuts <span>Admin</span></a><nav><a href="/admin.php">Dashboard</a><a href="/admin-flavors.php">Flavors</a><a href="/admin-packs.php">Packs</a><a href="/admin-orders.php">Orders</a><a class="active" href="/admin-inventory.php">Inventory</a><a href="/admin-promotions.php">Promotions</a><a href="/admin-content.php">Content</a><a href="/admin-reports.php">Reports</a><a href="/admin-notifications.php">Email</a><a href="/admin-marketing.php">Marketing</a><a href="/admin-audit.php">Audit</a></nav></header>
<main class="admin-shell"><p class="eyebrow">Production</p><h1>Flavor inventory</h1><section class="dashboard-kpis inventory-lease-kpis"><article class="kpi-card"><span>Active checkout holds</span><strong><?=(int)$reservationStats['active']?></strong><small>Bounded inventory reservations</small></article><article class="kpi-card <?=((int)$reservationStats['expired']>0?'kpi-alert':'')?>"><span>Expired holds</span><strong><?=(int)$reservationStats['expired']?></strong><small>Recovery worker should clear these</small></article><article class="kpi-card"><span>Payment review holds</span><strong><?=(int)$reservationStats['review_hold']?></strong><small>Protected from automatic release</small></article></section><?php if($error):?><div class="notice error"><?=htmlspecialchars($error)?></div><?php endif;?>
<table><thead><tr><th>Flavor</th><th>Available</th><th>Reserved</th><th>Tracking</th><th>Update</th></tr></thead><tbody>
<?php foreach($rows as $r):?><tr><td><?=htmlspecialchars($r['name'])?></td><td><?=(int)($r['available']??0)?></td><td><?=(int)($r['reserved']??0)?></td><td><?=!empty($r['track_inventory'])?'On':'Unlimited'?></td><td><form method="post" class="inline-admin"><input type="hidden" name="_csrf" value="<?=htmlspecialchars(csrf_token())?>"><input type="hidden" name="flavor_id" value="<?=(int)$r['id']?>"><label><input type="checkbox" name="track_inventory" value="1" <?=!empty($r['track_inventory'])?'checked':''?>> Track</label><input type="number" min="0" name="stock_on_hand" value="<?=(int)($r['stock_on_hand']??0)?>" placeholder="Stock"><input type="number" min="0" name="low_stock_threshold" value="<?=(int)($r['low_stock_threshold']??6)?>" placeholder="Low"><button class="button secondary">Save</button></form></td></tr><?php endforeach;?>
</tbody></table></main></body></html>
