<?php
declare(strict_types=1);
require dirname(__DIR__).'/src/bootstrap.php';
use FudgeDonuts\{Database,FoodComplianceService};
require_admin_roles(['super_admin','admin']);
$db=Database::connection();$svc=new FoodComplianceService($db);$error='';$notice='';
$id=(int)($_GET['id']??$_POST['flavor_id']??0);
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf($_POST['_csrf']??null);
 try{$svc->save($id,$_POST,(int)$_SESSION['admin_id']);$notice='Compliance profile saved.';}catch(Throwable $e){$error=$e->getMessage();}
}
$rows=$svc->all();$summary=$svc->summary();$current=$id?$svc->profile($id):null;
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Food Compliance · Fudge Donuts Admin</title><link rel="stylesheet" href="<?=htmlspecialchars(asset_url('/assets/app.css'))?>"></head><body class="admin-body">
<header class="admin-topbar"><a class="admin-brand" href="/admin.php">Fudge Donuts <span>Admin</span></a><nav><a href="/admin.php">Dashboard</a><a href="/admin-flavors.php">Flavors</a><a class="active" href="/admin-food-compliance.php">Food Compliance</a><a href="/admin-inventory.php">Inventory</a><a href="/admin-ingredient-lots.php">Ingredients</a><a href="/admin-orders.php">Orders</a></nav></header>
<main class="admin-shell"><div class="admin-page-head"><div><p class="eyebrow">Product safety</p><h1>Food Compliance</h1><p class="admin-welcome">Publish complete ingredient, allergen, storage, shelf-life and label information per flavor.</p></div></div>
<?php if($error):?><div class="notice error" role="alert"><?=htmlspecialchars($error)?></div><?php endif;?><?php if($notice):?><div class="notice" role="status"><?=htmlspecialchars($notice)?></div><?php endif;?>
<section class="dashboard-kpis"><article class="kpi-card"><span>Active flavors</span><strong><?=$summary['active']?></strong></article><article class="kpi-card"><span>Complete</span><strong><?=$summary['complete']?></strong></article><article class="kpi-card"><span>Published</span><strong><?=$summary['published']?></strong></article><article class="kpi-card <?=$summary['incomplete']?'kpi-alert':''?>"><span>Incomplete</span><strong><?=$summary['incomplete']?></strong></article></section>
<section class="dashboard-grid dashboard-secondary"><div class="dashboard-panel"><h2>Flavor readiness</h2><div class="dashboard-table-wrap"><table class="dashboard-table"><thead><tr><th>Flavor</th><th>Completeness</th><th>Published</th><th></th></tr></thead><tbody><?php foreach($rows as $row):?><tr><td><strong><?=htmlspecialchars($row['name'])?></strong></td><td><?=$row['completeness']['score']?>%<?php if($row['completeness']['missing']):?><small><?=htmlspecialchars(implode(', ',$row['completeness']['missing']))?></small><?php endif;?></td><td><?=((int)$row['published']&&$row['completeness']['complete'])?'Yes':'No'?></td><td><a class="link" href="/admin-food-compliance.php?id=<?=(int)$row['id']?>">Edit</a><?php if((int)$row['published']&&$row['completeness']['complete']):?> · <a class="link" target="_blank" href="/admin-food-label.php?flavor_id=<?=(int)$row['id']?>">Label</a><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></div>
<?php if($current):?><div class="dashboard-panel"><h2><?=htmlspecialchars($current['name'])?></h2><form method="post" class="admin-form"><input type="hidden" name="_csrf" value="<?=htmlspecialchars(csrf_token())?>"><input type="hidden" name="flavor_id" value="<?=$id?>"><label>Ingredient statement<textarea name="ingredient_statement" rows="5" required><?=htmlspecialchars($current['ingredient_statement'])?></textarea></label><label>Allergen statement<textarea name="allergen_statement" rows="3" required><?=htmlspecialchars($current['allergen_statement'])?></textarea></label><label>Shared-kitchen notice<textarea name="shared_kitchen_notice" rows="3"><?=htmlspecialchars($current['shared_kitchen_notice'])?></textarea></label><label>Storage instructions<textarea name="storage_instructions" rows="3" required><?=htmlspecialchars($current['storage_instructions'])?></textarea></label><div class="two"><label>Shelf life (days)<input type="number" min="1" max="365" name="shelf_life_days" required value="<?=htmlspecialchars((string)$current['shelf_life_days'])?>"></label><label>Net weight (oz)<input type="number" min=".01" step=".01" name="net_weight_oz" required value="<?=htmlspecialchars((string)$current['net_weight_oz'])?>"></label></div><label>Label version<input name="label_version" required value="<?=htmlspecialchars($current['label_version'])?>"></label><label class="check"><input type="checkbox" name="published" value="1" <?=(int)$current['published']?'checked':''?>> Publish to customers</label><button class="button">Save compliance profile</button></form></div><?php else:?><div class="dashboard-panel"><div class="dashboard-empty">Choose a flavor to edit its compliance profile.</div></div><?php endif;?></section></main></body></html>