<?php
declare(strict_types=1);
require dirname(__DIR__).'/src/bootstrap.php';

use FudgeDonuts\{AdminAuditService,Database,PackagingInventoryService,PackagingPurchasingService,SupplierPurchasingService};
require_admin_roles(['super_admin','admin','fulfillment']);

$db=Database::connection();$svc=new PackagingPurchasingService($db);$inv=new PackagingInventoryService($db);$audit=new AdminAuditService($db);$supplierSvc=new SupplierPurchasingService($db);$error='';$notice=(string)($_SESSION['pkg_po_flash']??'');unset($_SESSION['pkg_po_flash']);
$id=(int)($_GET['id']??$_POST['po_id']??0);
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf($_POST['_csrf']??null);
    try{
        $action=(string)($_POST['action']??'');
        if($action==='supplier_item'){
            $itemId=$svc->saveSupplierItem($_POST);
            $audit->record((int)$_SESSION['admin_id'],'packaging_supplier_item_saved','packaging_supplier_item',$itemId,'Packaging supplier item saved.',[],['supplier_id'=>(int)$_POST['supplier_id'],'material_id'=>(int)$_POST['material_id']]);
            $_SESSION['pkg_po_flash']='Packaging supplier mapping saved.';
        }elseif($action==='create_po'){
            $lines=[];foreach((array)($_POST['qty']??[]) as $itemId=>$qty)$lines[]=['supplier_item_id'=>(int)$itemId,'quantity_ordered'=>(int)$qty];
            $po=$svc->createPurchaseOrder((int)$_POST['supplier_id'],$lines,(string)($_POST['expected_at']??''),(string)($_POST['notes']??''),(int)$_SESSION['admin_id']);
            $audit->record((int)$_SESSION['admin_id'],'packaging_po_created','packaging_purchase_order',$po,'Packaging purchase order created.');
            $_SESSION['pkg_po_flash']='Packaging purchase order created.';header('Location: /admin-packaging-purchasing.php?id='.$po,true,303);exit;
        }elseif($action==='order'){
            $svc->markOrdered($id);$audit->record((int)$_SESSION['admin_id'],'packaging_po_ordered','packaging_purchase_order',$id,'Packaging purchase order marked ordered.');$_SESSION['pkg_po_flash']='Packaging PO marked ordered.';
        }elseif($action==='cancel'){
            $svc->cancel($id);$audit->record((int)$_SESSION['admin_id'],'packaging_po_cancelled','packaging_purchase_order',$id,'Packaging purchase order cancelled.');$_SESSION['pkg_po_flash']='Packaging PO cancelled.';
        }elseif($action==='receive'){
            $line=(int)$_POST['po_item_id'];$qty=(int)$_POST['quantity_received'];$svc->receive($line,$qty,(string)$_POST['received_at'],(string)($_POST['notes']??''),(int)$_SESSION['admin_id']);
            $audit->record((int)$_SESSION['admin_id'],'packaging_po_received','packaging_purchase_order',$id,'Packaging purchase order receipt recorded.',[],['po_item_id'=>$line,'quantity_received'=>$qty]);$_SESSION['pkg_po_flash']='Packaging receipt recorded and inventory updated.';
        }else throw new InvalidArgumentException('Unsupported packaging purchasing action.');
        header('Location: /admin-packaging-purchasing.php'.($id?'?id='.$id:''),true,303);exit;
    }catch(Throwable $e){$error=$e->getMessage();}
}
$recommendations=$svc->recommendations();$supplierItems=$svc->supplierItems(null,false);$suppliers=$supplierSvc->suppliers(true);$materials=$inv->materials();$pos=$svc->purchaseOrders();$current=$id?$svc->purchaseOrder($id):null;
$itemsBySupplier=[];foreach($supplierItems as $item)if((int)$item['active']&&(int)$item['supplier_active'])$itemsBySupplier[(int)$item['supplier_id']][]=$item;
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Packaging Purchasing · Fudge Donuts Admin</title><link rel="stylesheet" href="/assets/app.css"></head><body class="admin-body">
<header class="admin-topbar"><a class="admin-brand" href="/admin.php">Fudge Donuts <span>Admin</span></a><nav><a href="/admin.php">Dashboard</a><a href="/admin-packaging.php">Packaging</a><a class="active" href="/admin-packaging-purchasing.php">Packaging POs</a><a href="/admin-suppliers.php">Suppliers</a><a href="/admin-purchase-orders.php">Ingredient POs</a></nav></header>
<main class="admin-shell">
<div class="admin-page-head"><div><p class="eyebrow">Packaging procurement</p><h1>Packaging Purchasing</h1><p class="admin-welcome">Source fulfillment materials from the shared supplier directory and receive them directly into packaging inventory.</p></div></div>
<?php if($error):?><div class="notice error" role="alert"><?=htmlspecialchars($error)?></div><?php endif;?><?php if($notice):?><div class="notice" role="status"><?=htmlspecialchars($notice)?></div><?php endif;?>
<section class="dashboard-kpis"><article class="kpi-card <?=($recommendations['critical']>0?'kpi-alert':'')?>"><span>Supplier gaps</span><strong><?=$recommendations['critical']?></strong><small>Short materials without active supplier</small></article><article class="kpi-card"><span>Recommended spend</span><strong><?=money((int)$recommendations['estimated_cost_cents'])?></strong><small>Lowest-cost mapped suppliers</small></article><article class="kpi-card"><span>Open POs</span><strong><?=count(array_filter($pos,fn($p)=>in_array($p['status'],['ordered','partially_received'],true)))?></strong><small>Ordered / partially received</small></article><article class="kpi-card"><span>Supplier mappings</span><strong><?=count(array_filter($supplierItems,fn($i)=>(int)$i['active']===1))?></strong><small>Active packaging sources</small></article></section>

<section class="dashboard-panel"><div class="panel-head"><div><p class="eyebrow">Replenishment</p><h2>Recommended purchases</h2></div></div><div class="dashboard-table-wrap"><table class="dashboard-table"><thead><tr><th>Material</th><th>Shortage</th><th>Buy</th><th>Recommended supplier</th><th>Lead</th><th>Est. cost</th></tr></thead><tbody>
<?php if(!$recommendations['rows']):?><tr><td colspan="6" class="empty-cell">Packaging stock covers current demand and reorder points.</td></tr><?php endif;?>
<?php foreach($recommendations['rows'] as $row):$item=$row['supplier_item'];?><tr><td><strong><?=htmlspecialchars($row['name'])?></strong><small><?=htmlspecialchars($row['sku'])?></small></td><td><?=(int)$row['shortage_units']?></td><td><strong><?=(int)$row['recommended_order_quantity']?></strong></td><td><?php if($item):?><?=htmlspecialchars($item['supplier_name'])?><small><?=htmlspecialchars($item['supplier_sku'])?> · <?=money((int)$item['unit_cost_cents'])?> / unit</small><?php else:?><span class="danger">No supplier mapping</span><?php endif;?></td><td><?=$item?(int)$item['lead_time_days'].' days':'—'?></td><td><?=$item?money((int)$row['estimated_cost_cents']):'—'?></td></tr><?php endforeach;?>
</tbody></table></div></section>

<section class="dashboard-grid dashboard-secondary">
<div class="dashboard-panel"><div class="panel-head"><div><p class="eyebrow">Supplier catalog</p><h2>Map packaging material</h2></div></div><form method="post" class="admin-form"><input type="hidden" name="_csrf" value="<?=htmlspecialchars(csrf_token())?>"><input type="hidden" name="action" value="supplier_item"><label>Supplier<select name="supplier_id" required><?php foreach($suppliers as $s):?><option value="<?=(int)$s['id']?>"><?=htmlspecialchars($s['name'])?></option><?php endforeach;?></select></label><label>Material<select name="material_id" required><?php foreach($materials as $m):if(!(int)$m['active'])continue;?><option value="<?=(int)$m['id']?>"><?=htmlspecialchars($m['name'].' · '.$m['sku'])?></option><?php endforeach;?></select></label><label>Supplier SKU<input name="supplier_sku" maxlength="120"></label><div class="two"><label>Unit cost (cents)<input type="number" min="0" name="unit_cost_cents" value="0"></label><label>Lead time days<input type="number" min="0" max="365" name="lead_time_days" value="0"></label></div><label>Minimum order quantity<input type="number" min="1" name="min_order_quantity"></label><label class="check"><input type="checkbox" name="active" value="1" checked> Active</label><button class="button">Save supplier mapping</button></form></div>
<div class="dashboard-panel"><div class="panel-head"><div><p class="eyebrow">Supplier mappings</p><h2>Active sources</h2></div></div><div class="dashboard-table-wrap"><table class="dashboard-table"><thead><tr><th>Material</th><th>Supplier</th><th>Cost</th><th>Lead</th><th>MOQ</th></tr></thead><tbody><?php if(!$supplierItems):?><tr><td colspan="5" class="empty-cell">No packaging suppliers mapped.</td></tr><?php endif;?><?php foreach($supplierItems as $i):?><tr><td><?=htmlspecialchars($i['material_name'])?><small><?=htmlspecialchars($i['supplier_sku'])?></small></td><td><?=htmlspecialchars($i['supplier_name'])?></td><td><?=money((int)$i['unit_cost_cents'])?></td><td><?=(int)$i['lead_time_days']?> d</td><td><?=htmlspecialchars((string)($i['min_order_quantity']??'—'))?></td></tr><?php endforeach;?></tbody></table></div></div>
</section>

<section class="dashboard-panel"><div class="panel-head"><div><p class="eyebrow">Purchase orders</p><h2>Create packaging PO</h2></div></div>
<div class="packaging-po-create"><?php foreach($suppliers as $supplier):$supplierId=(int)$supplier['id'];$mapped=$itemsBySupplier[$supplierId]??[];if(!$mapped)continue;?><form method="post" class="card admin-form"><input type="hidden" name="_csrf" value="<?=htmlspecialchars(csrf_token())?>"><input type="hidden" name="action" value="create_po"><input type="hidden" name="supplier_id" value="<?=$supplierId?>"><h3><?=htmlspecialchars($supplier['name'])?></h3><?php foreach($mapped as $i):?><label><?=htmlspecialchars($i['material_name'])?> <small><?=money((int)$i['unit_cost_cents'])?> · MOQ <?=htmlspecialchars((string)($i['min_order_quantity']??'none'))?></small><input type="number" min="0" name="qty[<?=(int)$i['id']?>]" value="0"></label><?php endforeach;?><label>Expected date<input type="date" name="expected_at" min="<?=gmdate('Y-m-d')?>"></label><label>Notes<textarea name="notes"></textarea></label><button class="button secondary">Create draft PO</button></form><?php endforeach;?></div></section>

<section class="dashboard-grid dashboard-secondary"><div class="dashboard-panel"><div class="panel-head"><div><p class="eyebrow">PO ledger</p><h2>Packaging purchase orders</h2></div></div><div class="dashboard-table-wrap"><table class="dashboard-table"><thead><tr><th>PO</th><th>Supplier</th><th>Status</th><th>Expected</th><th>Total</th></tr></thead><tbody><?php if(!$pos):?><tr><td colspan="5" class="empty-cell">No packaging purchase orders.</td></tr><?php endif;?><?php foreach($pos as $po):?><tr><td><a href="/admin-packaging-purchasing.php?id=<?=(int)$po['id']?>"><strong><?=htmlspecialchars($po['po_number'])?></strong></a></td><td><?=htmlspecialchars($po['supplier_name'])?></td><td><?=htmlspecialchars(ucwords(str_replace('_',' ',$po['status'])))?></td><td><?=htmlspecialchars((string)$po['expected_at'])?></td><td><?=money((int)$po['total_cents'])?></td></tr><?php endforeach;?></tbody></table></div></div>
<?php if($current):?><div class="dashboard-panel"><div class="panel-head"><div><p class="eyebrow"><?=htmlspecialchars($current['po_number'])?></p><h2><?=htmlspecialchars($current['supplier_name'])?></h2></div></div><p>Status: <strong><?=htmlspecialchars(ucwords(str_replace('_',' ',$current['status'])))?></strong><?php if($current['expected_at']):?> · Expected <?=htmlspecialchars($current['expected_at'])?><?php endif;?></p><div class="dashboard-table-wrap"><table class="dashboard-table"><thead><tr><th>Material</th><th>Ordered</th><th>Received</th><th>Remaining</th><th>Receive</th></tr></thead><tbody><?php foreach($current['items'] as $line):?><tr><td><?=htmlspecialchars($line['material_name'])?></td><td><?=(int)$line['quantity_ordered']?></td><td><?=(int)$line['quantity_received']?></td><td><?=(int)$line['remaining_quantity']?></td><td><?php if((int)$line['remaining_quantity']>0 && in_array($current['status'],['ordered','partially_received'],true)):?><form method="post" class="packaging-receive-form"><input type="hidden" name="_csrf" value="<?=htmlspecialchars(csrf_token())?>"><input type="hidden" name="action" value="receive"><input type="hidden" name="po_id" value="<?=(int)$current['id']?>"><input type="hidden" name="po_item_id" value="<?=(int)$line['id']?>"><input type="number" name="quantity_received" min="1" max="<?=(int)$line['remaining_quantity']?>" value="<?=(int)$line['remaining_quantity']?>" aria-label="Receive <?=htmlspecialchars($line['material_name'])?>"><input type="datetime-local" name="received_at" value="<?=gmdate('Y-m-d\TH:i')?>" required><input name="notes" maxlength="2000" placeholder="Receipt notes"><button class="link">Receive</button></form><?php else:?>—<?php endif;?></td></tr><?php endforeach;?></tbody></table></div><div class="actions"><?php if($current['status']==='draft'):?><form method="post"><input type="hidden" name="_csrf" value="<?=htmlspecialchars(csrf_token())?>"><input type="hidden" name="action" value="order"><input type="hidden" name="po_id" value="<?=(int)$current['id']?>"><button class="button">Mark ordered</button></form><?php endif;?><?php if(in_array($current['status'],['draft','ordered'],true)):?><form method="post"><input type="hidden" name="_csrf" value="<?=htmlspecialchars(csrf_token())?>"><input type="hidden" name="action" value="cancel"><input type="hidden" name="po_id" value="<?=(int)$current['id']?>"><button class="button secondary">Cancel PO</button></form><?php endif;?></div></div><?php endif;?></section>
</main></body></html>