<?php
declare(strict_types=1);
require dirname(__DIR__).'/src/bootstrap.php';

use FudgeDonuts\{AdminAuditService,Database,FinishedGoodsAgingService};
require_admin_roles(['super_admin','admin','fulfillment']);

$db=Database::connection();$svc=new FinishedGoodsAgingService($db);$audit=new AdminAuditService($db);$error='';$notice=(string)($_SESSION['aging_flash']??'');unset($_SESSION['aging_flash']);

if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf($_POST['_csrf']??null);
    try{
        $action=(string)($_POST['action']??'');
        if($action==='settings'){
            $days=(int)($_POST['warning_days']??3);$svc->setWarningDays($days);
            $audit->record((int)$_SESSION['admin_id'],'finished_goods_aging_settings_updated','finished_goods_aging','global','Finished-goods aging warning horizon updated.',[],['warning_days'=>$days]);
            $_SESSION['aging_flash']='Aging warning horizon saved.';
        }elseif($action==='hold_expired'){
            $count=$svc->holdExpired();
            $audit->record((int)$_SESSION['admin_id'],'finished_goods_expired_held','finished_goods_aging','expired','Expired finished goods automatically placed on hold.',[],['count'=>$count]);
            $_SESSION['aging_flash']=$count.' expired batch'.($count===1?'':'es').' placed on hold.';
        }elseif($action==='disposition'){
            $batchId=(int)($_POST['batch_id']??0);$qty=(int)($_POST['quantity']??0);$reason=(string)($_POST['reason']??'');$notes=(string)($_POST['notes']??'');
            $id=$svc->disposition($batchId,$qty,$reason,$notes,(int)$_SESSION['admin_id']);
            $audit->record((int)$_SESSION['admin_id'],'finished_goods_disposition_recorded','finished_goods_disposition',$id,'Finished-goods disposition recorded.',[],['batch_id'=>$batchId,'quantity'=>$qty,'reason'=>$reason]);
            $_SESSION['aging_flash']='Finished-goods disposition recorded.';
        }else throw new InvalidArgumentException('Unsupported aging action.');
        header('Location: /admin-finished-goods-aging.php',true,303);exit;
    }catch(Throwable $e){$error=$e->getMessage();}
}
$svc->holdExpired();$summary=$svc->summary();$rows=$svc->rows();$history=$svc->dispositions(100);$warning=$svc->warningDays();
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Finished Goods Aging · Fudge Donuts Admin</title><link rel="stylesheet" href="/assets/app.css"></head><body class="admin-body">
<header class="admin-topbar"><a class="admin-brand" href="/admin.php">Fudge Donuts <span>Admin</span></a><nav><a href="/admin.php">Dashboard</a><a href="/admin-batches.php">Batches</a><a href="/admin-batch-allocation.php">Allocation</a><a class="active" href="/admin-finished-goods-aging.php">Aging</a><a href="/admin-production-qa.php">QA & Waste</a><a href="/admin-inventory.php">Inventory</a></nav></header>
<main class="admin-shell"><div class="admin-page-head"><div><p class="eyebrow">Waste prevention</p><h1>Finished-Goods Aging</h1><p class="admin-welcome">Hold expired batches, prioritize near-expiry stock, and account for every unit removed from saleable finished goods.</p></div><form method="post"><input type="hidden" name="_csrf" value="<?=htmlspecialchars(csrf_token())?>"><input type="hidden" name="action" value="hold_expired"><button class="button secondary">Hold expired now</button></form></div>
<?php if($error):?><div class="notice error" role="alert"><?=htmlspecialchars($error)?></div><?php endif;?><?php if($notice):?><div class="notice" role="status"><?=htmlspecialchars($notice)?></div><?php endif;?>
<section class="dashboard-kpis"><article class="kpi-card <?=($summary['expired_batches']>0?'kpi-alert':'')?>"><span>Expired</span><strong><?=$summary['expired_units']?></strong><small><?=$summary['expired_batches']?> batch<?=($summary['expired_batches']===1?'':'es')?> requiring disposition</small></article><article class="kpi-card <?=($summary['expiring_batches']>0?'kpi-alert':'')?>"><span>Expiring ≤ <?=$warning?> days</span><strong><?=$summary['expiring_units']?></strong><small><?=$summary['expiring_batches']?> batch<?=($summary['expiring_batches']===1?'':'es')?></small></article><article class="kpi-card"><span>No best-by date</span><strong><?=$summary['no_date_batches']?></strong><small>Remaining batches without aging date</small></article><article class="kpi-card"><span>Disposed · 30 days</span><strong><?=$summary['disposed_30d']?></strong><small>Units removed from finished goods</small></article></section>
<section class="dashboard-grid dashboard-secondary"><div class="dashboard-panel"><div class="panel-head"><div><p class="eyebrow">Aging inventory</p><h2>Remaining finished goods</h2></div></div><div class="dashboard-table-wrap"><table class="dashboard-table"><thead><tr><th>Batch</th><th>Flavor</th><th>Best by</th><th>Remaining</th><th>Age state</th><th>Disposition</th></tr></thead><tbody><?php if(!$rows):?><tr><td colspan="6" class="empty-cell">No remaining active or held finished goods.</td></tr><?php endif;?><?php foreach($rows as $row):?><tr><td><a href="/admin-batches.php?id=<?=(int)$row['id']?>"><strong><?=htmlspecialchars($row['batch_code'])?></strong></a><small><?=htmlspecialchars($row['status'])?></small></td><td><?=htmlspecialchars($row['flavor_name'])?></td><td><?=htmlspecialchars((string)($row['best_by_date']??'—'))?><?php if($row['days_remaining']!==null):?><small><?=((int)$row['days_remaining']>=0?(int)$row['days_remaining'].' days left':abs((int)$row['days_remaining']).' days past')?></small><?php endif;?></td><td><?=(int)$row['quantity_remaining']?></td><td><span class="aging-state aging-state-<?=htmlspecialchars($row['aging_state'])?>"><?=htmlspecialchars(ucwords(str_replace('-',' ',$row['aging_state'])))?></span></td><td><form method="post" class="aging-disposition-form"><input type="hidden" name="_csrf" value="<?=htmlspecialchars(csrf_token())?>"><input type="hidden" name="action" value="disposition"><input type="hidden" name="batch_id" value="<?=(int)$row['id']?>"><input type="number" name="quantity" min="1" max="<?=(int)$row['quantity_remaining']?>" value="<?=(int)$row['quantity_remaining']?>" aria-label="Disposition quantity for <?=htmlspecialchars($row['batch_code'])?>"><select name="reason" aria-label="Disposition reason"><option value="expired" <?=$row['aging_state']==='expired'?'selected':''?>>Expired</option><option value="quality">Quality</option><option value="damage">Damage</option><option value="donation">Donation</option><option value="sample">Sample</option><option value="other">Other</option></select><input name="notes" maxlength="2000" placeholder="Notes" aria-label="Disposition notes"><button class="link">Record</button></form></td></tr><?php endforeach;?></tbody></table></div></div>
<div class="dashboard-panel"><div class="panel-head"><div><p class="eyebrow">Settings</p><h2>Aging horizon</h2></div></div><form method="post" class="admin-form"><input type="hidden" name="_csrf" value="<?=htmlspecialchars(csrf_token())?>"><input type="hidden" name="action" value="settings"><label>Warn when best-by is within<input type="number" name="warning_days" min="1" max="30" value="<?=$warning?>"></label><button class="button secondary">Save warning horizon</button></form><div class="allergen-callout"><strong>Automatic safety hold</strong><p>The scheduled aging worker places expired active batches on hold. Disposition is always an explicit operator action so remaining inventory cannot disappear without an audit record.</p></div></div></section>
<section class="dashboard-panel"><div class="panel-head"><div><p class="eyebrow">Audit history</p><h2>Recent dispositions</h2></div></div><div class="dashboard-table-wrap"><table class="dashboard-table"><thead><tr><th>When</th><th>Batch</th><th>Flavor</th><th>Qty</th><th>Reason</th><th>Recorded by</th><th>Notes</th></tr></thead><tbody><?php if(!$history):?><tr><td colspan="7" class="empty-cell">No finished-goods dispositions recorded.</td></tr><?php endif;?><?php foreach($history as $d):?><tr><td><?=htmlspecialchars($d['created_at'])?></td><td><?=htmlspecialchars($d['batch_code'])?></td><td><?=htmlspecialchars($d['flavor_name'])?></td><td><?=(int)$d['quantity']?></td><td><?=htmlspecialchars(ucfirst($d['reason']))?></td><td><?=htmlspecialchars((string)($d['admin_email']??''))?></td><td><?=htmlspecialchars($d['notes'])?></td></tr><?php endforeach;?></tbody></table></div></section>
</main></body></html>