<?php
declare(strict_types=1);
require dirname(__DIR__).'/src/bootstrap.php';
use FudgeDonuts\{AdminAuditService,AdminService,Database,PromotionService};
require_admin_roles(['super_admin','admin']);
$db=Database::connection();$svc=new PromotionService($db);$audit=new AdminAuditService($db);$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf($_POST['_csrf']??null);try{$svc->save($_POST);$audit->record((int)$_SESSION['admin_id'],'promotion_saved','promotion',(string)($_POST['code']??$_POST['name']??''),'Promotion configuration saved.',[],$_POST);header('Location: /admin-promotions.php');exit;}catch(Throwable $e){$error=$e->getMessage();}}
$rules=(new AdminService($db))->discounts();
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/assets/app.css"><title>Promotions · Admin</title></head><body class="admin-body">
<header class="admin-topbar"><a class="admin-brand" href="/admin.php">Fudge Donuts <span>Admin</span></a><nav><a href="/admin.php">Dashboard</a><a href="/admin-flavors.php">Flavors</a><a href="/admin-packs.php">Packs</a><a href="/admin-orders.php">Orders</a><a href="/admin-inventory.php">Inventory</a><a class="active" href="/admin-promotions.php">Promotions</a><a href="/admin-content.php">Content</a><a href="/admin-reports.php">Reports</a><a href="/admin-notifications.php">Email</a></nav></header>
<main class="admin-shell"><p class="eyebrow">Marketing</p><h1>Promotions</h1><?php if($error):?><div class="notice error"><?=htmlspecialchars($error)?></div><?php endif;?>
<table><thead><tr><th>Name</th><th>Code</th><th>Type</th><th>Value</th><th>Usage</th><th>Status</th></tr></thead><tbody><?php foreach($rules as $d):?><tr><td><?=htmlspecialchars($d['name'])?></td><td><?=htmlspecialchars($d['code']??'Automatic')?></td><td><?=htmlspecialchars($d['type'])?></td><td><?=$d['type']==='percent'?(int)$d['value'].'%':money((int)$d['value'])?></td><td><?=(int)$d['usage_count']?><?=($d['usage_limit']!==null?'/'.(int)$d['usage_limit']:'')?></td><td><?=(int)$d['active']?'Active':'Inactive'?></td></tr><?php endforeach;?></tbody></table>
<h2>Add promotion</h2><form method="post" class="admin-form"><input type="hidden" name="_csrf" value="<?=htmlspecialchars(csrf_token())?>"><input name="name" required placeholder="Name"><input name="code" placeholder="Promo code (blank = automatic)"><select name="type"><option value="percent">Percent</option><option value="fixed">Fixed amount (cents)</option></select><input type="number" name="value" min="1" required placeholder="Value"><input type="number" name="min_units" min="0" value="0" placeholder="Minimum boxes"><input type="number" name="min_subtotal_cents" min="0" value="0" placeholder="Minimum subtotal cents"><input name="usage_limit" type="number" min="1" placeholder="Usage limit"><input name="starts_at" placeholder="YYYY-MM-DD HH:MM:SS"><input name="ends_at" placeholder="YYYY-MM-DD HH:MM:SS"><input name="sort_order" type="number" value="0"><label><input type="checkbox" name="active" value="1" checked> Active</label><button class="button">Save promotion</button></form>
</main></body></html>
