<?php
declare(strict_types=1);
require dirname(__DIR__).'/src/bootstrap.php';
use FudgeDonuts\{AdminAuditService,Database,InventoryService,ProductionPlanningService};
require_admin_roles(['super_admin','admin','fulfillment']);
$db=Database::connection();$svc=new InventoryService($db);$audit=new AdminAuditService($db);$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf($_POST['_csrf']??null);
 try{$flavorId=(int)$_POST['flavor_id'];$before=[];foreach($svc->rows() as $row)if((int)$row['id']===$flavorId){$before=$row;break;}$svc->setInventory($flavorId,!empty($_POST['track_inventory']),(int)$_POST['stock_on_hand'],(int)$_POST['low_stock_threshold']);$after=[];foreach($svc->rows() as $row)if((int)$row['id']===$flavorId){$after=$row;break;}$audit->record((int)$_SESSION['admin_id'],'inventory_updated','flavor',$flavorId,'Flavor inventory updated.',$before,$after);header('Location: /admin-inventory.php');exit;}catch(Throwable $e){$error=$e->getMessage();}
}
$rows=$svc->rows();$reservationStats=$svc->reservationStats();
$history=max(7,min(180,(int)($_GET['history']??env('PRODUCTION_HISTORY_DAYS','28'))));
$forecastDays=max(1,min(60,(int)($_GET['days']??7)));
$safetyDays=max(0,min(30,(int)($_GET['safety']??env('PRODUCTION_SAFETY_DAYS','2'))));
$production=(new ProductionPlanningService($db))->forecast($history,$forecastDays,$safetyDays);
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="<?=htmlspecialchars(asset_url('/assets/app.css'))?>"><title>Inventory · Admin</title></head><body class="admin-body">
<header class="admin-topbar"><a class="admin-brand" href="/admin.php">Fudge Donuts <span>Admin</span></a><nav><a href="/admin.php">Dashboard</a><a href="/admin-flavors.php">Flavors</a><a href="/admin-packs.php">Packs</a><a href="/admin-orders.php">Orders</a><a href="/admin-procurement-plan.php">Procurement Plan</a><a href="/admin-shipping.php">Shipping</a><a class="active" href="/admin-inventory.php">Inventory</a><a href="/admin-ingredient-lots.php">Ingredients</a><a href="/admin-promotions.php">Promotions</a><a href="/admin-content.php">Content</a><a href="/admin-reports.php">Reports</a><a href="/admin-notifications.php">Email</a><a href="/admin-marketing.php">Marketing</a><a href="/admin-audit.php">Audit</a><a href="/admin-operations.php">Operations</a></nav></header>
<main class="admin-shell"><p class="eyebrow">Production</p><h1>Flavor inventory</h1><section class="dashboard-kpis inventory-lease-kpis"><article class="kpi-card"><span>Active checkout holds</span><strong><?=(int)$reservationStats['active']?></strong><small>Bounded inventory reservations</small></article><article class="kpi-card <?=((int)$reservationStats['expired']>0?'kpi-alert':'')?>"><span>Expired holds</span><strong><?=(int)$reservationStats['expired']?></strong><small>Recovery worker should clear these</small></article><article class="kpi-card"><span>Payment review holds</span><strong><?=(int)$reservationStats['review_hold']?></strong><small>Protected from automatic release</small></article></section><?php if($error):?><div class="notice error"><?=htmlspecialchars($error)?></div><?php endif;?>
<table><thead><tr><th>Flavor</th><th>Available</th><th>Reserved</th><th>Tracking</th><th>Update</th></tr></thead><tbody>
<?php foreach($rows as $r):?><tr><td><?=htmlspecialchars($r['name'])?></td><td><?=(int)($r['available']??0)?></td><td><?=(int)($r['reserved']??0)?></td><td><?=!empty($r['track_inventory'])?'On':'Unlimited'?></td><td><form method="post" class="inline-admin"><input type="hidden" name="_csrf" value="<?=htmlspecialchars(csrf_token())?>"><input type="hidden" name="flavor_id" value="<?=(int)$r['id']?>"><label><input type="checkbox" name="track_inventory" value="1" <?=!empty($r['track_inventory'])?'checked':''?>> Track</label><input type="number" min="0" name="stock_on_hand" value="<?=(int)($r['stock_on_hand']??0)?>" placeholder="Stock"><input type="number" min="0" name="low_stock_threshold" value="<?=(int)($r['low_stock_threshold']??6)?>" placeholder="Low"><button class="button secondary">Save</button></form></td></tr><?php endforeach;?>
</tbody></table>
<section class="dashboard-panel production-plan-panel"><div class="panel-head"><div><p class="eyebrow">Forecast</p><h2>Production plan</h2><p>Demand is based on actual flavor units sold in the selected history window.</p></div><a class="button secondary" href="/admin-production-plan.csv.php?history=<?=$history?>&days=<?=$forecastDays?>&safety=<?=$safetyDays?>">Export CSV</a></div>
<form method="get" class="inline-admin production-plan-controls"><label>History days<input type="number" name="history" min="7" max="180" value="<?=$history?>"></label><label>Forecast days<input type="number" name="days" min="1" max="60" value="<?=$forecastDays?>"></label><label>Safety days<input type="number" name="safety" min="0" max="30" value="<?=$safetyDays?>"></label><button class="button secondary">Recalculate</button></form>
<div class="dashboard-kpis"><article class="kpi-card"><span>Recent demand</span><strong><?=(int)$production['totals']['recent_units']?></strong><small>Flavor units in <?=$history?> days</small></article><article class="kpi-card"><span><?=$forecastDays?>-day forecast</span><strong><?=(int)$production['totals']['forecast_units']?></strong><small>Expected flavor units</small></article><article class="kpi-card"><span>Suggested prep</span><strong><?=(int)$production['totals']['suggested_prep']?></strong><small>Including <?=$safetyDays?> safety day<?=($safetyDays===1?'':'s')?></small></article><article class="kpi-card <?=((int)$production['totals']['at_risk']>0?'kpi-alert':'')?>"><span>At risk</span><strong><?=(int)$production['totals']['at_risk']?></strong><small>Flavors below target coverage</small></article></div>
<div class="dashboard-table-wrap"><table class="dashboard-table"><thead><tr><th>Flavor</th><th>Risk</th><th>Recent</th><th>Daily</th><th>Forecast</th><th>Available</th><th>Days cover</th><th>Suggested prep</th></tr></thead><tbody><?php foreach($production['rows'] as $p):?><tr><td><strong><?=htmlspecialchars($p['name'])?></strong></td><td><span class="production-risk production-risk-<?=htmlspecialchars($p['risk'])?>"><?=htmlspecialchars(ucwords(str_replace('-',' ',$p['risk'])))?></span></td><td><?=(int)$p['recent_units']?></td><td><?=htmlspecialchars(number_format((float)$p['daily_velocity'],2))?></td><td><?=(int)$p['forecast_units']?> <small>+ <?=(int)$p['safety_units']?> safety</small></td><td><?=$p['available']===null?'Untracked':(int)$p['available']?></td><td><?=$p['days_cover']===null?'—':htmlspecialchars(number_format((float)$p['days_cover'],1))?></td><td><strong><?=(int)$p['suggested_prep']?></strong></td></tr><?php endforeach;?></tbody></table></div></section>
</main></body></html>
