<?php
declare(strict_types=1);
require dirname(__DIR__).'/src/bootstrap.php';
use FudgeDonuts\{CatalogRepository,Database,FoodComplianceService,ReviewService,SeoService};

$db=Database::connection();$catalog=new CatalogRepository($db);
$slug=trim((string)($_GET['slug']??''));
$flavor=$catalog->flavorBySlug($slug);
if(!$flavor){
    \FudgeDonuts\HttpResponseService::send(
        404,
        'That flavor isn’t available.',
        'The flavor link may be old, seasonal, or no longer active.',
        [
            ['label'=>'See current flavors','href'=>'/#flavors'],
            ['label'=>'Build a box','href'=>'/builder.php?size=12']
        ]
    );
}
$compliance=(new FoodComplianceService($db))->publicProfile((int)$flavor['id']);
$reviewService=new ReviewService($db);$reviewAggregate=$reviewService->aggregate((int)$flavor['id']);$approvedReviews=$reviewService->approvedForFlavor((int)$flavor['id'],20);
$canReview=!empty($_SESSION['user_id']) && $reviewService->canReview((int)$_SESSION['user_id'],(int)$flavor['id']);
$seo=new SeoService($catalog,(string)env('APP_URL','https://example.com'));$schemaData=$seo->flavorSchema($flavor);
if($reviewAggregate['count']>0)$schemaData['aggregateRating']=['@type'=>'AggregateRating','ratingValue'=>$reviewAggregate['average'],'reviewCount'=>$reviewAggregate['count'],'bestRating'=>5,'worstRating'=>1];
$schema=json_encode($schemaData,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);$canonical=$seo->canonical('/flavor.php?slug='.rawurlencode($slug));
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=htmlspecialchars($flavor['name'])?> · Fudge Donuts</title><meta name="description" content="<?=htmlspecialchars($flavor['description'])?>"><link rel="canonical" href="<?=htmlspecialchars($canonical)?>"><meta property="og:title" content="<?=htmlspecialchars($flavor['name'])?> · Fudge Donuts"><meta property="og:description" content="<?=htmlspecialchars($flavor['description'])?>"><meta property="og:type" content="product"><meta property="og:url" content="<?=htmlspecialchars($canonical)?>"><meta property="og:image" content="<?=htmlspecialchars($seo->canonical($flavor['image_path']?:'/images/placeholder.png'))?>"><meta property="og:site_name" content="Fudge Donuts"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="<?=htmlspecialchars($flavor['name'])?> · Fudge Donuts"><meta name="twitter:description" content="<?=htmlspecialchars($flavor['description'])?>"><meta name="twitter:image" content="<?=htmlspecialchars($seo->canonical($flavor['image_path']?:'/images/placeholder.png'))?>"><script type="application/ld+json"><?=$schema?></script><link rel="stylesheet" href="<?=htmlspecialchars(asset_url('/assets/app.css'))?>"><?=analytics_script()?></head><body>
<a class="skip-link" href="#main-content">Skip to main content</a>
<header class="nav"><a class="brand" href="/">Fudge Donuts</a><nav><a href="/#flavors">Flavors</a><a href="/builder.php?size=12">Build a Box</a><a href="/cart.php">Cart</a></nav></header>
<main id="main-content" class="section flavor-detail"><div class="flavor-detail-grid"><div><img class="flavor-detail-image" src="<?=htmlspecialchars($flavor['image_path']?:'/images/placeholder.png')?>" alt="<?=htmlspecialchars($flavor['name'])?>" decoding="async" fetchpriority="high"></div><div><p class="eyebrow"><?=!empty($flavor['seasonal'])?'Seasonal flavor':'Fudge Donut flavor'?></p><h1><?=htmlspecialchars($flavor['name'])?></h1><p class="lead"><?=htmlspecialchars($flavor['description'])?></p><?php if((int)$flavor['sold_out']):?><div class="notice error">Currently sold out.</div><?php endif;?><?php if((int)$flavor['surcharge_cents']):?><p><strong>Premium flavor:</strong> +<?=money((int)$flavor['surcharge_cents'])?> per donut in custom boxes.</p><?php endif;?><div class="food-info"><section><h2>Ingredients</h2><p><?=$compliance?nl2br(htmlspecialchars($compliance['ingredient_statement'])):(trim((string)$flavor['ingredients'])!==''?nl2br(htmlspecialchars($flavor['ingredients'])):'Ingredient information coming soon.')?></p></section><section><h2>Allergens</h2><p><?=$compliance?nl2br(htmlspecialchars($compliance['allergen_statement'])):(trim((string)$flavor['allergens'])!==''?nl2br(htmlspecialchars($flavor['allergens'])):'No allergen statement has been entered yet. Contact us before ordering if you have a food allergy.')?></p></section><?php if($compliance):?><section><h2>Storage & shelf life</h2><p><?=nl2br(htmlspecialchars($compliance['storage_instructions']))?></p><p>Recommended shelf life: <?=(int)$compliance['shelf_life_days']?> days · Net wt. <?=number_format((float)$compliance['net_weight_oz'],2)?> oz.</p></section><?php endif;?></div><div class="allergen-callout"><strong>Food allergy notice</strong><p><?=htmlspecialchars($compliance&&$compliance['shared_kitchen_notice']?$compliance['shared_kitchen_notice']:'Products may be prepared in a shared kitchen. Review the allergen information for every flavor in your box before ordering.')?></p></div><div class="actions"><a class="button" href="/builder.php?size=12">Build a box</a><a class="button secondary" href="/#flavors">See all flavors</a></div></div></div>
<section class="flavor-reviews"><div class="panel-head"><div><p class="eyebrow">Verified customer reviews</p><h2><?=htmlspecialchars($reviewAggregate['count']>0?number_format((float)$reviewAggregate['average'],1).' / 5':'No reviews yet')?></h2><?php if($reviewAggregate['count']>0):?><p><?=str_repeat('★',(int)round($reviewAggregate['average']))?><?=str_repeat('☆',5-(int)round($reviewAggregate['average']))?> · <?=(int)$reviewAggregate['count']?> approved review<?=((int)$reviewAggregate['count']===1?'':'s')?></p><?php endif;?></div><?php if($canReview):?><a class="button secondary" href="/review.php?slug=<?=urlencode($slug)?>">Write a review</a><?php endif;?></div>
<?php if(!$approvedReviews):?><div class="dashboard-empty"><strong>Be the first verified purchaser to review this flavor.</strong></div><?php else:?><div class="review-grid"><?php foreach($approvedReviews as $review):?><article class="customer-review"><p class="review-stars" aria-label="<?=(int)$review['rating']?> out of 5 stars"><?=str_repeat('★',(int)$review['rating'])?><?=str_repeat('☆',5-(int)$review['rating'])?></p><?php if($review['title']):?><h3><?=htmlspecialchars($review['title'])?></h3><?php endif;?><p><?=nl2br(htmlspecialchars($review['body']))?></p><small>Verified customer · <?=htmlspecialchars(substr((string)$review['created_at'],0,10))?></small></article><?php endforeach;?></div><?php endif;?></section>
</main></body></html>
